"""initial

Revision ID: 54ccc166d30b
Revises: 
Create Date: 2026-03-13 09:53:14.114614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '54ccc166d30b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.create_table('parkings_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('total_spots', sa.Integer(), nullable=False),
    sa.Column('available_spots', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('coordinates', sa.JSON(), nullable=True),
    sa.Column('boundaries', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parkings_table_id'), 'parkings_table', ['id'], unique=False)
    op.create_table('camera_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rtsp_url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'MAINTENANCE', 'ERROR', name='camerastatus'), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('is_calibrated', sa.Boolean(), nullable=False),
    sa.Column('monitored_spot_ids', sa.JSON(), nullable=False),
    sa.Column('parking_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parking_id'], ['parkings_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camera_table_id'), 'camera_table', ['id'], unique=False)
    op.create_index(op.f('ix_camera_table_parking_id'), 'camera_table', ['parking_id'], unique=False)
    op.create_table('vehicles_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plate_number', sa.String(length=12), nullable=False),
    sa.Column('features', pgvector.sqlalchemy.Vector(512), nullable=True, comment='Вектор признаков автомобиля'),
    sa.Column('is_inside', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('last_camera_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['last_camera_id'], ['camera_table.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_table_id'), 'vehicles_table', ['id'], unique=False)
    op.create_index(op.f('ix_vehicles_table_is_inside'), 'vehicles_table', ['is_inside'], unique=False)
    op.create_index(op.f('ix_vehicles_table_plate_number'), 'vehicles_table', ['plate_number'], unique=True)
    op.create_table('spots_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('spot_number', sa.String(length=10), nullable=False),
    sa.Column('spot_type', sa.Enum('STANDARD', 'DISABLED', name='spottype'), nullable=False),
    sa.Column('spot_status', sa.Enum('FREE', 'OCCUPIED', 'RESERVED', name='spotstatus'), nullable=False),
    sa.Column('spot_coordinates', sa.JSON(), nullable=False),
    sa.Column('occupied_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('parking_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['current_vehicle_id'], ['vehicles_table.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parking_id'], ['parkings_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parking_id', 'spot_number', name='uq_parking_spot')
    )
    op.create_index(op.f('ix_spots_table_id'), 'spots_table', ['id'], unique=False)
    op.create_index(op.f('ix_spots_table_parking_id'), 'spots_table', ['parking_id'], unique=False)
    op.create_index(op.f('ix_spots_table_spot_status'), 'spots_table', ['spot_status'], unique=False)
    op.create_table('tracking_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['camera_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spot_id'], ['spots_table.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tracking_time', 'tracking_table', ['timestamp', 'vehicle_id'], unique=False)
    op.create_index(op.f('ix_tracking_table_camera_id'), 'tracking_table', ['camera_id'], unique=False)
    op.create_index(op.f('ix_tracking_table_id'), 'tracking_table', ['id'], unique=False)
    op.create_index(op.f('ix_tracking_table_timestamp'), 'tracking_table', ['timestamp'], unique=False)
    op.create_index(op.f('ix_tracking_table_vehicle_id'), 'tracking_table', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracking_table_vehicle_id'), table_name='tracking_table')
    op.drop_index(op.f('ix_tracking_table_timestamp'), table_name='tracking_table')
    op.drop_index(op.f('ix_tracking_table_id'), table_name='tracking_table')
    op.drop_index(op.f('ix_tracking_table_camera_id'), table_name='tracking_table')
    op.drop_index('idx_tracking_time', table_name='tracking_table')
    op.drop_table('tracking_table')
    op.drop_index(op.f('ix_spots_table_spot_status'), table_name='spots_table')
    op.drop_index(op.f('ix_spots_table_parking_id'), table_name='spots_table')
    op.drop_index(op.f('ix_spots_table_id'), table_name='spots_table')
    op.drop_table('spots_table')
    op.drop_index(op.f('ix_vehicles_table_plate_number'), table_name='vehicles_table')
    op.drop_index(op.f('ix_vehicles_table_is_inside'), table_name='vehicles_table')
    op.drop_index(op.f('ix_vehicles_table_id'), table_name='vehicles_table')
    op.drop_table('vehicles_table')
    op.drop_index(op.f('ix_camera_table_parking_id'), table_name='camera_table')
    op.drop_index(op.f('ix_camera_table_id'), table_name='camera_table')
    op.drop_table('camera_table')
    op.drop_index(op.f('ix_parkings_table_id'), table_name='parkings_table')
    op.drop_table('parkings_table')
    # ### end Alembic commands ###
