events {}

http {
    server {
        listen 8080;

        location /users/ {
            proxy_pass http://auth-service:8003;
        }

        location /auth/ {
            proxy_pass http://auth-service:8003;
        }

        location = /payments {
            proxy_pass http://payment-service:8005;
        }

        location /payments/ {
            proxy_pass http://payment-service:8005;
        }

        location = /fines {
            proxy_pass http://payment-service:8005;
        }

        location /fines/ {
            proxy_pass http://payment-service:8005;
        }

        location /payment-events {
            proxy_pass http://payment-service:8005;
        }

        location /webhooks/mock {
            proxy_pass http://payment-service:8005;
        }

        location /notifications/ {
            proxy_pass http://notification-service:8006;
        }

        location /devices/ {
            proxy_pass http://notification-service:8006;
        }

        location / {
            proxy_pass http://parking-management-service:8000;
        }
    }
}
