events {}

http {
    server {
        listen 8080;

        # Auth-эндпоинты → auth_service (порт 8003)
        location /users/ {
            proxy_pass http://auth_service:8003;
        }

        location /auth/ {
            proxy_pass http://auth_service:8003;
        }

        # Всё остальное → parking_management_service (порт 8000)
        location / {
            proxy_pass http://parking_service:8000;
        }
    }
}